## **Python lists are flexible but slow for numerical computing because they:**
- Store elements as pointers instead of a continuous block of memory.
- ck vectorized operations, relying on loops instead.
- Have significant overhead due to dynamic typing.

## **NumPy's Superpowers:**
- Faster than Python lists (C-optimized backend)
- Uses less memory (efficient storage)
- Supports vectorized operations (no explicit loops needed)
- Has built-in mathematical functions

In [4]:
# zip function
l1 = [1,2,3]
l2 = [4,5,6]
zipped_list  = list(zip(l1,l2))
print(zipped_list)

[(1, 4), (2, 5), (3, 6)]


## **SPEED TEST**

In [5]:
# Using python list
import numpy as np
import time

size = 1_000
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(end-start)
print(add[0:10])

0.00032448768615722656
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [6]:
import numpy as np
import time

size = 1_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))
start = time.time()
add = l1+l2
end = time.time()

print(end-start)
print(add[0:10])

0.0006635189056396484
[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# From the above speed test it is very clear that numpy array is much faster than our python list.

## **Creating numpy array**

In [8]:
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [9]:
# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
print("Type of array is : " , type(arr1))
print("Shape of array is :", arr2.shape)

Type of array is :  <class 'numpy.ndarray'>
Shape of array is : (2, 3)


In [15]:
# Vectorization in numpy : numpy avoids loops using vectorization and applies condition directly to an entire array.
# USES (SIMDB) :-> SINGLE INSTRUCTTION , MULTIPLE DATA

In [16]:
# Python list
list1 = [1,2,3,4]
list_squares = [x**2 for x in list1]
print(list_squares)

[1, 4, 9, 16]


In [17]:
# numpy array
import numpy as np
arr3 = np.array([1,2,3,4])
arr4 = arr3**2
print(arr4)

[ 1  4  9 16]


In [18]:
# lets calculate time for squaring a python list and a numpy array!

In [19]:
# Python list
list1 = [1,2,3,4]
start = time.time()
list_squares = [x**2 for x in list1]
end = time.time()
print(end - start)
print(list_squares)

0.00032782554626464844
[1, 4, 9, 16]


In [20]:
arr3 = np.array([1,2,3,4])
start = time.time()
arr4 = arr3**2
end = time.time()
print(end - start)
print(arr4)

0.0002467632293701172
[ 1  4  9 16]
