In [4]:
import numpy as np

### **array form python list**

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
arr1 = np.array([1,2,3,4,5,6]) # 1D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [6]:
# all elemets in numpy array should be of same dtype

### **1. Zeros**

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **2. ones**

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### **3.full**

In [10]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

### **4.eye**

In [12]:
np.eye(4) #can be given of any order eample 2 , 3 ,4 ..

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **5.arange**

In [13]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

### **6. Linspace**

In [17]:
# gives equally spaced arrays 
np.linspace(1 , 100 , 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

### **arrays properties**

In [18]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
myarr.shape

(4, 3)

In [21]:
myarr.size #(4,3) -> 4*3 = 12

12

In [23]:
myarr.ndim  # 2D array

2

In [24]:
myarr.dtype

dtype('int64')

### **changing dtype of narray**

In [25]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [26]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
myarr.shape  # four rows and 3 cols

(4, 3)

In [29]:
# i can reshape this array

In [32]:
reshaped = myarr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
myarr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [36]:
myarr.flatten() # gives array of 1D only elements no rows and cols 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])