In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3]

np.int64(4)

In [9]:
flat[3:6]

array([4, 5, 6])

In [11]:
flat[:5] #same as flat[0:5] starts from zero by defualt if nothing given

array([1, 2, 3, 4, 5])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [13]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [17]:
b[0]=4444

In [20]:
print(flat)
print(b)

[   1    2    3 4444    5    6    7    8    9   10   11   12]
[4444    5    6    7]


In [21]:
# SLICING RETURNS A VIEW AND NOT A COPY SO CHNAGES IN THE SLICE AFFECTS THE ORIGINAL ARRAY 
# THIS IS BEACUSE FOR MEMORY EFFICIENCY 

In [24]:
b = flat[3:7].copy()
b

array([4444,    5,    6,    7])

In [27]:
# do not want the oiginal array to be affected use copy()

In [28]:
org = np.array([1,2,3,4])

In [29]:
copied = org.copy()

In [31]:
copied[0] = 11111

In [32]:
print(copied)
print(org)

[11111     2     3     4]
[1 2 3 4]


In [34]:
arr = np.array([1,54,23,53,2,3,34,5,6])

In [36]:
arr[[1,4,6]]    #returns aray of elements present on the respective positiions

array([54,  2, 34])

### **boolean masking**

In [39]:
arr[arr>23] #give some condition and elements which staisfy this condition will be in the output

array([54, 53, 34])

### **Exercises for Practice**

In [47]:
#1
arr = np.random
print(arr)

<module 'numpy.random' from 'C:\\Users\\Lenovo\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>


In [52]:
#2
arr1 = np.array([1.1,2.2,3.3])
print(arr1)
arr2 = arr1.astype(np.int64)
print(arr2)
print(arr2.dtype)

[1.1 2.2 3.3]
[1 2 3]
int64


In [53]:
#3
arr3 = np.array([1,2,3,4,5,6])
arr3[[1,3,5]]

array([2, 4, 6])

In [57]:
#4
arr4 = np.array([1,2,3,4,5,6,7,8,9])
arr5 = arr4.reshape(3,3)
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#5
arr6 = np.array([20,30,45,67,89,90,98,23,22,12,1])
arr6[arr6>50]

array([67, 89, 90, 98])