In [1]:
import numpy as np

In [3]:

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[1]

array([4, 5, 6])

In [8]:
np.sum(arr , axis = 0)  #row elements are added (down each column)

array([12, 15, 18])

In [9]:
np.sum(arr , axis = 1) # column elements  are added (across each row)

array([ 6, 15, 24])

### **2. Indexing in Multidimensional Arrays**

In [10]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [11]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [14]:
print(arr[1:3 , 0:2])

[[4 5]
 [7 8]]


### **3. Indexing in 3D Arrays**

In [15]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [17]:
print(arr3D [1,1,2])

12


In [18]:
print(arr3D [1,0,2])

9


### **4. Practical Example: Selecting Data Along Axes**

In [19]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [20]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


### **5. Changing Data Along an Axis**

In [21]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
